-- Generated [
-- Format      : Eclipse keywords (ASCII)
-- Exported by : Petrel 2024.4.0 Schlumberger
-- User name   : oa2414
-- Date        : Sunday, November 02 2025 22:20:18
-- Project     : Fractional_flow.pet
-- Generated ]

INIT                                   -- Generated : Petrel

GRIDFILE                               -- Generated : Petrel
  0 0 /

GRIDUNIT                               -- Generated : Petrel
  METRES /

MAPUNITS                               -- Generated : Petrel
  METRES /

MAPAXES                                -- Generated : Petrel
  0 -995 0 5 1000 5 /

PINCH                                  -- Generated : Petrel
  4* ALL /

