-- Generated [
-- Format      : Eclipse keywords (ASCII)
-- Exported by : Petrel 2024.4.0 Schlumberger
-- User name   : oa2414
-- Date        : Sunday, November 02 2025 22:20:18
-- Project     : Fractional_flow.pet
-- Generated ]

EQUIL                                  -- Generated : Petrel
           890          325          885            0          880            0 0 0 0 /

RPTRST                                 -- Generated : Petrel
  BASIC=3 FLOWS BG BO BW /

RPTSOL                                 -- Generated : Petrel
  SOIL SWAT SGAS RESTART=2 FIP SSOL /

